language: node_js
node_js: node
branches:
  only:
  - master
  - /^[0-9]+(\.[0-9]+|x)?\.x$/
addons:
  apt:
    packages:
      # Japanese
      - language-pack-ja
      - japan*
      # Chinese
      - language-pack-zh*
      - chinese*
      # Korean
      - language-pack-ko
      - korean*
      # Fonts
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core
jobs:
  include:
    - stage: tests
      script:
      - npm run build
      - npm run lint
      - npm run test:axe
      - |
        if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
            echo "Pull request with secure environment variables, running Sauce tests...";
            npm run test:sauce || travis_terminate 1;
        else
            echo "Not a pull request and/or no secure environment variables, running headless tests...";
            npm run test:headless || travis_terminate 1;
        fi
      env:
        - SAUCE_USERNAME: Gaudi1
        # SAUCE_ACCESS_KEY
        - secure: bwPUP8HCJ4x/VQHYT83fw28MF6fZqcCFYYLQIuYl5d8QXPuHNiON+36YSEkIix/2AjuQR8OtNqy7MPem013QUzEl9ayJ+P/Kto3hN84D6fNj4DXKUtDywDeAs6B0hv3OZZIUJ2ixqClyGDRoK9M51NzS3d9Nts8rEDTJY5CqnD7s+0mOUXfmr7ehStQfs4JdsGApdp5ByA7btC6t3vNAUSoGOlnfKGb4VP/cCXAS64Suy/8Q09fCCKr2BMswQwR6hwb52EJ50W9JbpXu/S0DwrwwM5ZGCG4+SSXqrMoaWXeoOjjQ+tdTx+Rj/cvYO0IE9vJvEMubFCzjs57d2r9IwoKmJg27Fh7YPlZk4YEhcge2vDO9AmlGKGDKeEYco4fXelAmmCcFjmrWXjH8Uc31n2wZj4yYg6AKU2M+GvMYNmh+aI1qGJ+urpQigYdf8IWpqryW19wiOzRm+N6JhdFGlfgnJMEv/OmdTwGOXKA1Qlmc0Bv8ZjWHa6bVMrwnueygoUwc7rWYQg0SjIaW8zhTWwy2JkBoCD1/TpKYTNOdL4VSaxpRSCQn4uAlJ2rNBIyv7FM0S7ycKMTVQGXIyaRo28vKUEGUDYGYWbu++5fBxRfaHWeE79ZFE823LyFQetTUmr7ms/i4pqkaM/m+q840s34lLwmupSoUoVBAGezVsk8=
    - stage: visual-difference-tests
      script:
      - npm run build
      - |
        if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
          echo "Running visual difference tests...";
          npm run test:diff || travis_terminate 1;
        fi
      env:
        # VISUAL_DIFF_S3_ID
        - secure: GGPx9fJpdWd2BcvfXnFQQBBswAazOEWgZXnqmrRma045OpvlJeeUYn3N3gamz3nS2Mv0u3Y0j3ViAbEgDjo4hbW4Iz4/8tmv0T/59qYnco8ONXBnUEytJxMy8B6dOHT+rX/Fgn/4+dxWItWc4igG1FryK4TpGn1JrcsmlPHoJJZRQyUYqrKk4OfUzjs2LOaGHGyy2Sm+bXfSOWt12VnMBrHzwMRsrnhdZNzx/XqKTbGPWuV/YTLqJ0azqz3DoxhmmrllgnGgbKncTtZN2vSzGqlxTjS0Dn+CDnXP5LAvN6u7OLqI2jo/10XBG8ZHe6W/szun/nIKnIHBX87HDr0+39B5R9kMR6PHgGG/fRnDSva/ssKHgjRAoMxznG74j7Efk+MegYf8DSctMGwA+NxCMZFoNM5gEDIKo7w7N5RdDK9PC3kZaZajJqskQIr1uE2hVlBZONXtOvkQ0fJX4eiHym7ClWJW8QWXVU7FyiZfj0WE4MWwYzGSa/ve5EpvKCP1Wat276qnJRIdrSCsxxYk2u8w9qgyXr8jbhkWHzkaX9Ff/82X4/POCxoXibDMOF60DHxWniKCdhaviUEf1leiTjidJqr3dXRCLjCTD3GlLTxQVt6JlGDdY+0Dy/IcUblrCG5t4Ym4S6hbkIWx5cVPPQSl6t5ELq37Gof9FSvUQSg=
        # VISUAL_DIFF_S3_SECRET
        - secure: hETcU1ZRPPz7ipofSeUj8fLkdM9JJda/Qg/oXU83FqZ/y/LZya6jMJjBfcHgEGsCLmVOPLw4lj2+pcyA6ZprJuujdS56elnbWPYUa4iwCbPN7ayfFQQjQx3jo3LYd7jFlCilgMT+Q+s+SnVfmV1Wa91N5WOpINpi7NzIarBRhWVeoiCQJmaabAX2pIn4G5VnBIE562SJULq+05Ucavl9zWrSFHDsMqMtcVcHG7TI6BExENJf76iutEk/YqWdaSvk5LY4xLrO29tThZBVJ7lX5wQGa3MkmlJkHZqxoONBWbGsKfrwh5I7QHExkj8PYYfvpYHQd+VugFrSkDTW3wHsoe/cmrzVe8aEbpHfUSPpO5HOkTdOqy92NVjyh4MOE7hJexmQsYRD+zjFzL4AS876hOdjrf/FS5ume843MvZseSZiCpK7uHTQWwVmitib/dNJdy8YyWoAyceWHpz46QOArrECVYOFhMKYuPrNy3gYY05kCLHCEW24pVN1ToRW2Gp6Z3Z3YblfWShjFHl3eU8riOPeCU9RaBV1k1UuP0C5POyFDPS12K8glPNIJ6dbp6GyI6KKW3iYuX/O3G4w/evO/AMy9nQPL4tUOPU5gQsPvr4Z77+bluP9VqEd3o1VBC6IBwLEcc8tzO+5EAeRbj9THU7zDmoIQH0oRHpIo+elg/8=
    - stage: deploy
      script: npm run build
      after_success: frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
      env:
        - REPO_NAME=core
        - OWNER_NAME=BrightspaceUI
      deploy:
        provider: npm
        email: d2ltravisdeploy@d2l.com
        skip_cleanup: true
        api_key:
          # 57c4......d343
          secure: IitMXMxHrtsjCy3eucLs/mxja8e27DRpxT1YnA7HM6nCpKEr+SzPaHqV4tSNfX8fmKvqhyR3SRijPWnGahaZNVAPlN0l01MSEaG419o3QIKFzSgpNZLjNe5BsGTH3CFC5yPgtrU6ILW2Et1pb1+oixghXSifybxxan4aJKwBuri1DnrijmBnlEyog1Wglra1e7GzwZnEohDitHWKqO2V6uE+v1LmDtnHMzKoEjEeD/iHk1/oKdfsbZLEcZ+l6xU3gORBMskG+XT8EPgPOpfnuCiL0tqJ+ZFcP2hbNrzMMKs/k5TAmvL0DJyvmDfjlBXLik4aHKX6GmYGfhfktBCEN4hl8rmo9eBoQxJuzWWnCJq5BxVRGxaBZg7yZK5qZYR8cUwS5t241LqDgMK4rQP6J6cImCZ1Fe93t9yMd3GsurSHIByHwwQ3tuY4Xj3f6Nr/skGYrS9azqRtREWsRY4rsiudcKuTQGsDfLMpEN6ZGZQBXrYgKZpCrgIUiK5PyggbzTfOfpSrxe4oBD6IIb6bITYPPU5rXnE4EMOLY6AUn5OBxR/ACkooccFa7gHxlgVaNAy+RRIFk4sW6NAbADZXzy1U+jp8QsCzZBU0gmjNLShD0uuUfWSdv75qq3eKlwBzrlI6TpADoGmsFxoO3Yc6d0YGOmcxWVu6ZRuqeyVTZ9I=
        on:
          repo: BrightspaceUI/core
          tags: true
env:
  global:
  # GITHUB_RELEASE_TOKEN
  - secure: AX/0lBWUVfZM8rxdyK1rmO5QP1oXIWS8m5pgcjNBxHtC1bWPQsyvLRyqdlcWmDfuJsVuUkwAO67njgnfacVsLi/P55dsd+amZuRmgb9IcdLEBy5IAerymeXT+OkhizDSVaYtRrDK5AHUPjDqUj2E554WwuPMdCulfwJ70PgAUjLYsJbUgpH1eym9SnoHjYj6OTajmOwxHZl09sEJL+qSHOX+j2vCVQhKMLPpnXodeonVGBCT29X1ad9OFZ/RFMliGNU89a/TysPfJP0IspA/CD7GG/cqPAhTt4Q6+ChccG34j+6fVWZM32tblYPGKgV5iVaLcI0wYzMZOwavlpgUb5Gw5KCxtHivsrCNwarFuNTKGepCQTcad0/3P/O4iRMg8cznIbpn+/D90MN/V/NGWZQylrIJeTJWWoYtaWLVnO77aRl1RQoTcGGz06jxkXdsq48qrQnhhdWfMoED40tv9sscB8fgit4WYxlvDhlNF0ybP26u5EArBN2E72QrQDMFKECdPQBuTsTB5Jr2YSpEy98qLqJ2Z382VfcQWRbcKctJsqNeK/WQhoT52c+IHEBR6N7Bvuy9aaPRvprVzFKhQv3vkE4566ud66NeYRrhVDj9cOhrHjh92CjZM549kV47IHZsyDOazmDEV+oXXqlDPXSJPywprnCWnOHxLY3ia0A=
